// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP0lRKQ-Cy5DkdOssiwrP-lbOTY4mfZSU',
    appId: '1:928656242844:web:d5cdeae6d9e2db4c379559',
    messagingSenderId: '928656242844',
    projectId: 'helloworld-adi-lncts',
    authDomain: 'helloworld-adi-lncts.firebaseapp.com',
    storageBucket: 'helloworld-adi-lncts.appspot.com',
    measurementId: 'G-0ZMEKZBXV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXqtT33ZpERThmX49otIbBzfH49X2m8XU',
    appId: '1:928656242844:android:6bb22e9d534ff0fa379559',
    messagingSenderId: '928656242844',
    projectId: 'helloworld-adi-lncts',
    storageBucket: 'helloworld-adi-lncts.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlpb-q3445omt8p8cXMKRhSS2lgFIrRPs',
    appId: '1:928656242844:ios:0ea8ade93a3467be379559',
    messagingSenderId: '928656242844',
    projectId: 'helloworld-adi-lncts',
    storageBucket: 'helloworld-adi-lncts.appspot.com',
    iosBundleId: 'com.example.helloworld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlpb-q3445omt8p8cXMKRhSS2lgFIrRPs',
    appId: '1:928656242844:ios:0ea8ade93a3467be379559',
    messagingSenderId: '928656242844',
    projectId: 'helloworld-adi-lncts',
    storageBucket: 'helloworld-adi-lncts.appspot.com',
    iosBundleId: 'com.example.helloworld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP0lRKQ-Cy5DkdOssiwrP-lbOTY4mfZSU',
    appId: '1:928656242844:web:b594c747692b6ff4379559',
    messagingSenderId: '928656242844',
    projectId: 'helloworld-adi-lncts',
    authDomain: 'helloworld-adi-lncts.firebaseapp.com',
    storageBucket: 'helloworld-adi-lncts.appspot.com',
    measurementId: 'G-3SXFTRDFXM',
  );
}
